import { createElement } from "lwc";
import GDD_CommunicationHomePanel from "c/gDD_CommunicationHomePanel";

describe("c-g-d-d-communication-home-panel", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-g-d-d-communication-home-panel", {
      is: GDD_CommunicationHomePanel
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
